config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , expect: [:index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name , length: { maximum: 20 } , presence: true
  validates :body , length: { minimum: 2 , maximum: 30 }, presence: true
  validates :age , numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 150 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  def index
    @message = Message.new
    @messages = Message.all.order(:id)
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end

  private
  def message_params
    params.require(:message).permit(:name, :age, :body)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= csrf_meta_tags %>
    <nav class="navbar">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Message Board</a>
        </div>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

  名前:
  <%= f.text_field :name, class: "form-control" %>

  年齢:
  <%= f.text_field :age, class: "form-control" %>

  内容:
  <%= f.text_area :body, class: "form-control", style: "resize: none"  %>
  <%= f.submit class: "btn btn-sm btn-primary", style: "margin-top: 1%" %>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ一覧
  </div>

  <div class="panel-body">
    <% @messages.each do |message| %>
      <div style="margin-top: 0.25%">
        <span class="label label-info"><%= message.name %>（<%= message.age %>歳）</span>
        <%= message.body %>
        (
        <%= message.updated_at.in_time_zone('Asia/Tokyo') %>
        )
        (
        <%= link_to "edit" , edit_message_path(message) %>
        <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
        )
        <br>
      </div>
    <% end %>
  </div>
</div>

<%= render 'form' %>